Repository YOGIITSU-App/YOGIITSU_back, pull requests merged in 2025-05, with the labels that each got.

#53 chore: CORS 설정을 환경변수로 변경하고 CI/CD에 시크릿 키 연동
  .github/workflows/cicd.yml
  src/main/java/com/YOGIITSU/config/SecurityConfig.java
Labels: ⚙️ chore

#59 feat: 건물 상세 조회 및 즐겨찾기 여부 조회 API 구현
  src/main/java/com/YOGIITSU/config/handler/GlobalExceptionHandler.java
  src/main/java/com/YOGIITSU/controller/BuildingController.java
  src/main/java/com/YOGIITSU/converter/BuildingConverter.java
  src/main/java/com/YOGIITSU/dto/ResponseDto/BuildingDetailResponseDto.java
  src/main/java/com/YOGIITSU/dto/ResponseDto/BuildingInfoResponseDto.java
  src/main/java/com/YOGIITSU/dto/ResponseDto/DepartmentResponseDto.java
  src/main/java/com/YOGIITSU/dto/ResponseDto/FacilityResponseDto.java
  src/main/java/com/YOGIITSU/dto/ResponseDto/FloorImageResponseDto.java
  src/main/java/com/YOGIITSU/entity/Building.java
  src/main/java/com/YOGIITSU/entity/BuildingFacility.java
  src/main/java/com/YOGIITSU/entity/BuildingFloorImage.java
  src/main/java/com/YOGIITSU/entity/BuildingTag.java
  src/main/java/com/YOGIITSU/entity/Department.java
  src/main/java/com/YOGIITSU/exception/building/BuildingNotFoundException.java
  src/main/java/com/YOGIITSU/repository/BuildingRepository.java
  src/main/java/com/YOGIITSU/repository/FavoriteRepository.java
  src/main/java/com/YOGIITSU/service/BuildingService.java
  src/test/java/com/YOGIITSU/service/BuildingServiceTest.java
Labels: ✨feature

#52 feat: 사용자용 문의 기능 구현
  .gitignore
  src/main/java/com/YOGIITSU/controller/InquiryController.java
  src/main/java/com/YOGIITSU/dto/RequestDto/InquiryRequestDto.java
  src/main/java/com/YOGIITSU/dto/ResponseDto/InquiryListResponseDto.java
  src/main/java/com/YOGIITSU/dto/ResponseDto/InquiryResponseDto.java
  src/main/java/com/YOGIITSU/entity/Inquiry.java
  src/main/java/com/YOGIITSU/entity/InquiryState.java
  src/main/java/com/YOGIITSU/repository/InquiryRepository.java
  src/main/java/com/YOGIITSU/service/InquiryService.java
Labels: ✨feature

#63 docs: 문의 API에 Swagger summary 어노테이션 추가
  src/main/java/com/YOGIITSU/controller/InquiryController.java
Labels: 📝 docs

#67 refactor: 문의 API 응답 구조 리팩토링 및 상세 조회 방식 통합
  src/main/java/com/YOGIITSU/controller/InquiryController.java
  src/main/java/com/YOGIITSU/dto/ResponseDto/InquiryListResponseDto.java
  src/main/java/com/YOGIITSU/dto/ResponseDto/InquiryResponseDto.java
  src/main/java/com/YOGIITSU/service/InquiryService.java
Labels: ♻️refactor

#68 feat: 토큰 재발급 API 구현 및 로그인 응답 포맷 변경
  src/main/java/com/YOGIITSU/controller/AuthController.java
  src/main/java/com/YOGIITSU/controller/MemberController.java
  src/main/java/com/YOGIITSU/service/MemberService.java
  src/test/java/com/YOGIITSU/controller/AuthControllerTest.java
  src/test/java/com/YOGIITSU/service/MemberServiceTest.java
Labels: ✨feature, ♻️refactor

#72 feat: 건물 상세정보 반환값에 정렬 기능 추가
  src/main/java/com/YOGIITSU/converter/BuildingConverter.java
  src/main/java/com/YOGIITSU/entity/Building.java
  src/main/java/com/YOGIITSU/entity/BuildingFacility.java
  src/main/java/com/YOGIITSU/entity/BuildingTag.java
  src/main/java/com/YOGIITSU/entity/Department.java
  src/test/java/com/YOGIITSU/converter/BuildingConverterTest.java
Labels: ✨feature

#73 refactor: 문의 상세 응답 필드 보완 및 시간 설정 개선
  src/main/java/com/YOGIITSU/dto/ResponseDto/InquiryResponseDto.java
Labels: ♻️refactor
